### ISSUE TITLE
Wow!

### ISSUE THREAD

**Issue by AndreyNazarchuk** [alejandroliu/pocketmine-plugins#11]
You are a good Plugin maker!
Do you have a server?
If no, can you help me write plugins for mine?
If yes, Can you tell me whats wrong with my plugin?

**Comment by alejandroliu** [comment]
Not a bug

**Comment by ifvictr** [comment]
@AndreyNazarchuk You have seriously got to stop spamming repository with invalid issues. And this wouldn't be the place to ask people to make plugins for you or anything to do with your plugins.

**Comment by AndreyNazarchuk** [comment]
Where else can I reach you?
