### ISSUE TITLE
IDs

### ISSUE THREAD

**Issue by AndreyNazarchuk** [alejandroliu/pocketmine-plugins#12]
For ItemCasePE:
Can you re add the feature of allowing multiple items in a case, and allowing to specify the id?
because not everything is available in creative and i dont want to use /give every time

**Comment by alejandroliu** [comment]
Not planning to do this. Since its all open source you can make those changes yourself.

**Comment by AndreyNazarchuk** [comment]
Actually its OK now, because I realized if you are holding a lot of the
same item it puts 4 of them in the case
