### ISSUE TITLE
join.message1 and join.message2 

### ISSUE THREAD

**Issue by mightysun99** [alejandroliu/pocketmine-plugins#13]
These messages don't seem to display correctly please refer to image attached for an example.
![img_0225](https://cloud.githubusercontent.com/assets/8927830/8147400/ce1397ec-12aa-11e5-8022-1bd4289404db.PNG)
This was taken using the latest version of both plugins.

**Comment by alejandroliu** [comment]
That is an issue with your SimpleAuth configuration.

Did you recently upgraded SimpleAuth?  If so, you need to delete your old messages.yml.

**Comment by mightysun99** [comment]
Yes this fixed it thankyou.
