### ISSUE TITLE
Pvp is disabled

### ISSUE THREAD

**Issue by AndreyNazarchuk** [alejandroliu/pocketmine-plugins#14]
After downloading latest source of SpawnMgr and editing it to give different armor/items to different ranks, it blocks pvp :/
Also the no-drops thing no longer works.
I deleted the pvp code (another plugin handles it) and did not touch any of the drop code.
should I delete the maker file?
yes I checked the config, and edited the config in the plugin.

**Comment by alejandroliu** [comment]
So are you saying you edited the config.yml or did you change the source directly?

**Comment by AndreyNazarchuk** [comment]
Changed source, it should be working because it gives armor based on ranks
now, come to think of it, I did update the server today. I am pretty sure
its because of PocketMine, sorry for bothering you.
