### ISSUE TITLE
GoldStd issue and feature request

### ISSUE THREAD

**Issue by ghost** [alejandroliu/pocketmine-plugins#15]
hello, first of all, thanks for coding the best pocketmine plugins I never seen :)
well, About GoldStd, I'm facing a crash when a player touch a sign on my server, you said on thread that this bug has fixed, but i think nope, here is:

Error: Call to undefined function aliuly\goldstd\isCreative()
File: GoldStd/src/aliuly/goldstd/SignMgr
Line: 262
Type: E_ERROR

Also, i know that isn`t the place to ask that, but I wish to know if you can implement a auto-spawning system for shopkeepers, because this is the substitute of the retro sign shops :p

I'm having to:
1: Spawn a dummy player
2: Execute the login command for him
3: tp him to the especified coordinates
4: Spawn the shopkeeper on his position
5: kick the dummy

That works, i did with using a bash script, but I can't control yaw and pitch :(

also i'm throuble about using new skins for merchant's, i tried renaming a png file to another.skin but I got a zlib_decode error, maybe this need more explaination...

thank you for you time.

**Comment by barnesybro** [comment]
What are you on about why do you keep emailing me

**Comment by ghost** [comment]
what? how I'll know about that? you are not the only people that said me that o.o
just click on 'unsubscribe', thats seems to be a github bug

**Comment by PEMapModder** [comment]
[unwatch this repo.](../watch)

**Comment by alejandroliu** [comment]
Should have been fixed in the latest GoldStd. 

Also added an option to the spawn command to spawn with x,y,z,yaw,pitch

**Comment by ghost** [comment]
Thank you

works like a charm...
maybe on future you could add a option for spawn the npc "forever" on some place, respawning then after each server reboot, anyway, it's woking fine for what i need, :)

keep up you good work!
