### ISSUE TITLE
LiveSigns issue

### ISSUE THREAD

**Issue by ghost** [alejandroliu/pocketmine-plugins#16]
hi, here I am again :p

 well, I,m using LiveSigns for query some servers... something new that I trying and it envolves showing the server online players in real time on a sign, well, whatever...

after setting up 9 servers I figured that my server TPS goes down, and don't even can walk anymore :p
 I take some timings and i see that LiveSigns are spamming tasks slowing down the server (really at freezing point, and my machine have powerfull resources...)

  here one timings result: http://timings.aikar.co/?url=11829177

I tried changing the tile refresh rate with a high value without result...
maybe LiveSigns are launching one task inside of another one in a loop?

well, Hope this have a solution :)

**Comment by alejandroliu** [comment]
Yes, the Query stuff was implemented rather quickly.  Though would be useful to have available.  It was in my todo list to optimize it later.  I wasn't expecting for people to start using it right away, and for that many servers.

Anyway, the problem with the Query is that it is run from the main thread.  (Quickest implementation), but it actually should be done from a AsyncTask (in a different thread).

Haven't have time to get around implementing that.

This actually requires additional though on how tasks are schedule within LiveSigns, as some signs are meant to be updated more slowly (i.e. Internet signs) whereas some signs are meant to be updated quickly (Query and PHP signs).  Right now, slow signs (Internet) are async, whereas quick signs are done in the main thread.

**Comment by alejandroliu** [comment]
Can you test https://github.com/alejandroliu/pocketmine-plugins/releases/tag/LiveSigns-1.1.1dev1?

**Comment by ghost** [comment]
Working flawless now :)

I did a stress test here and there's no more TPS slowdowns, I don't know how the server will react with a lot of players online, but I think that will run at full speed now.

The only issue that I found is that the signs isn't displaying query exeption's, but I think this is for a best performance right? this way LiveSigns will not update the signs with useless info for normal players...

well, I think that's solved, thank you!

**Comment by alejandroliu** [comment]
The queries are now done as an asynctask so it should not experience slow downs.

Query exceptions should now be shown on the console (and/or server.log).

I leave this ticket open a few days, and if no additional issues I reported I will close and post the update through the official channels.

**Comment by barnesybro** [comment]
Can you help me with my server

**Comment by iVertx** [comment]
Found a new issue...

The signs aren't updating automatically, The plugin are only updating tiles when the first player join and stops there, breking the [Online/Max] player count, also, I having trouble with MOTD, I'm using `$this->getServer->getNetwork-setName("Blah");` for set some dynamic MOTD'S related to what's happening on the server queried, It works perfectely but LiveSigns are only fetching the original server MOTD configured on the properties of target server... Anything I can do about that?  thanks

**Comment by ghost** [comment]
Found a new issue...

The signs aren't updating automatically, The plugin are only updating tiles when the first player join and stops there, breking the [Online/Max] player count :/

also, I having trouble with MOTD, I'm using $this->getServer->getNetwork-setName("Blah"); on a plugin localized on the queried server, for set some dynamic MOTD'S related to what's happening on the server queried, It works perfectely but LiveSigns are only fetching the original server MOTD configured on the properties of target server... Anything I can do about that? thanks

/\* edit */

Here some info about the signs:
`LiveSign: hg1
[16:54:34] [Server thread/INFO]: -   -
[16:54:34] [Server thread/INFO]: {HostName}
[16:54:34] [Server thread/INFO]: [{Players}/{MaxPlayers}]
[16:54:34] [Server thread/INFO]: -   -HostName        [HG1]
[16:54:34] [Server thread/INFO]: -   -GameType        SMP
[16:54:34] [Server thread/INFO]: -   -GameName        MINECRAFTPE
[16:54:34] [Server thread/INFO]: -   -Version v0.11.0 alpha
[16:54:34] [Server thread/INFO]: -   -Plugins PocketMine-MP 1.5dev-1244
[16:54:34] [Server thread/INFO]: -   -Map     xturbulence
[16:54:34] [Server thread/INFO]: -   -Players 0
[16:54:34] [Server thread/INFO]: -   -MaxPlayers      24
[16:54:34] [Server thread/INFO]: -   -HostIp  0.0.0.0
[16:54:34] [Server thread/INFO]: -   -HostPort        22001
[16:54:34] [Server thread/INFO]: -   -RawPlugins      PocketMine-MP 1.5dev-1244
[16:54:34] [Server thread/INFO]: -   -Software        PocketMine-MP 1.5dev-1244
[16:54:34] [Server thread/INFO]: -    tstamp: 2015-07-07 16:53:56`
ls cfg hg1
`[16:55:24] [Server thread/INFO]: LiveSign: hg1
[16:55:24] [Server thread/INFO]: -type: query
[16:55:24] [Server thread/INFO]: -content: 93.188.161.146,22001`

The test server that is quering this one above are located at 93.188.161.146:19133 if you want to see with your eyes what is the problem... (test with two or more devices) the signs are located at Survival Games lobby...

btw, when I do `ls show` the signs is updated, but, just one time...

**Comment by alejandroliu** [comment]
Can you show me the output of:

     /ls show <id>

and 

    /ls cfg <id>

Where <id> is the query?

**Comment by alejandroliu** [comment]
Can you try deleting your config.yml (or at least change the expire-cache to 200)?

Also, the MOTD trick you do with 

```
$this->getServer->getNetwork-setName("Blah");
```

Only applies to RakLib connections.  Since we are doing a Query that doesn't work.  You need to catch QueryRegenerateEvent and use $event->setServerName("Blah");

**Comment by ghost** [comment]
well, changing the expire cache i could see that the signs are updating :p but very slowly, no matter how faster "tile updates" are setted, but i'm pretty sure that is a query fault, quering one server, waiting the result then quering another seem to take a long time if the plugin have a lot of servers to query...

what I'm trying to do in my network is probally the closest way to simulate the BungeeCoord effect on pmmp serves, but, infortunatelly is hard if not impossible to obtain some info from another servers without using the slow query (maybe a RCON trick? /_or maybe making LiveSigns to read the last line of a text file? this way I can fwrite some info about the server on a txt file, and then display it on a sign, this will solve all speed issues_/), anyway, thank you for the tip about MOTD, and sorry if I did you lost your time :p

**Comment by alejandroliu** [comment]
Yes. Because it is query it is not updated immediately. 

Specifically the server that answers the queries only updates its data once every 10 seconds.  So querying more frequently will not help. 

The new version you can tune a number on caching settings.

**Comment by alejandroliu** [comment]
EDIT...

So, Query data in a PocketMine server is only updated once every 30 seconds (I timed it).  You may be able to change it by handling QueryRegenerateEvent and using a different timeout value.

On the other hand, LiveSigns has a number of timers:
1. tile-updates : So how often tiles get updated from internal data (i.e. PHP code, {vars} or cached signs).
2. cache-signs: how long sign text will be cached (by default).
3. expire-cache: How often we check for cached signs to be expired.

Also individual entries in "signs.yml" can have a max cached age with the "max-age" setting.
If that is not specified, it would use the config.yml max-age, unless the Fetcher class overrides that.  For example, queries are cached for 8 seconds.  (RIght now).

**Comment by ghost** [comment]
so, I'll try out handling QRE for that, but I think that this will help but not much, since all the `fetch<-connection->query update` process will  take some while... the sign updates and the query updates need to be strictly synced for get constant data about the target server, 

anyway, constantly signs updates, (and query updates on the target server I think) will drop down the server performance, and my goal is make that faster and lag free (php7 will help :p),

Thinking a little bit I found a way for make this process more simplier, and taking less resources... simply taking info about if the server is offline, and the displaying something like "13 of 16 Games running" I think I can do it using php instead of query (this way, speeding up the process, but i need think more about how is the better way for do that), and using some shell scripts to check servers... this way will be more easier for the hub's server's to handle the data about a bunch of external servers, 8 seconds or more of delay will be just fine if i do that...

thanks.

**Comment by alejandroliu** [comment]
OK
