### ISSUE TITLE
Folder

### ISSUE THREAD

**Issue by Pub4Game** [alejandroliu/pocketmine-plugins#19]
Why You don't have enough folders?)
![default](https://cloud.githubusercontent.com/assets/11244874/8790526/78e83fec-2f57-11e5-9080-bd08f8ddf0b3.PNG)

**Comment by PEMapModder** [comment]
Namespaces are used to create more systematic code. This is an invalid issue.

**Comment by Pub4Game** [comment]
Where the common folder?

**Comment by PEMapModder** [comment]
The common folder is injected into plugins when compiling.
https://github.com/alejandroliu/pocketmine-plugins/tree/master/libcommon/src/aliuly/common

**Comment by Pub4Game** [comment]
I'm sorry, I didn't know))) Thanks for explaining
