### ISSUE TITLE
libcommon and GrabBag

### ISSUE THREAD

**Issue by Pyszko** [alejandroliu/pocketmine-plugins#21]
Hi. I have one question.
Why plugin can't create folder? I enable debug on pocketmine.yml
And how to i can make multi query on lobby?

Survival 14/15
Factions 12/20
Skyblock 10/25

And how to make 36/60 on lobby?
lbsg have this. 

Or can make /query (GrabBag) to livesign or motd?

Sorry for bad english :/

**Comment by alejandroliu** [comment]
So, I don't know what you mean with "plugin can't create folder".

To do multi query on lobby you first need to add your other servers, i.e.:

```
/query add survival _ip_ _port_
/query add factions _ip_ _port_
/query add skyblock _ip_ _port_
```

Then you can do:

```
/query summary
```

If you want to do a motd thing you should use libcommon and try using the example file.

LiveSign has support for query and motd data already.

**Comment by Pyszko** [comment]
Query work, but how to can make this on server list? (Multi query) or how to use libcommon?
![screenshot_2015-08-17-14-49-20](https://cloud.githubusercontent.com/assets/13818864/9305184/636f4d74-44ef-11e5-869c-e816cac5106b.png)

I have 2 servers:
Survival 12/20
Factions 15/20
Lobby 2/10

How to make 29/50 in lobby?

Sorry for my very bad english.

**Comment by alejandroliu** [comment]
Ugh... forgot how to do that.  Perhaps you should post your question in the pocketmine forums.
