### ISSUE TITLE
Players cant use the command login 

### ISSUE THREAD

**Issue by ZGamerOficial** [alejandroliu/pocketmine-plugins#23]
You have to fix this problem.because when i enter or others enter they cant login.so fix this and update or your plugins! and in manyworlds is your plugin no? Why others players with no op can put /mw create ? And all commands for manyworlds.they can put all commands.fix this or make an update.thanks!

**Comment by alejandroliu** [comment]
OK, I will post an update to ManyWorlds.
In the meantime it can be downloaded 
https://github.com/alejandroliu/pocketmine-plugins/releases/tag/ManyWorlds-2.0.2

**Comment by ZGamerOficial** [comment]
Thanks for the update! Great job!and remember update all your plugins! Because they work great!
