### ISSUE TITLE
Cannot use SimpleAuth's authenticateByLastIP: true

### ISSUE THREAD

**Issue by inxomnyaa** [alejandroliu/pocketmine-plugins#24]
You cannot use the authenticateByLastIP: true of SimpleAuth

**Comment by alejandroliu** [comment]
What version of SimpleAuth are you using?

**Comment by inxomnyaa** [comment]
I use v1.7.1
Tried with Huawai and iPhone, ip's didn't changed

**Comment by alejandroliu** [comment]
SimpleAuth 1.7.1 uses now the authenticateByLastUniqueId setting.  The authenticateByLastIP is ignored.
