### ISSUE TITLE
ZHO.INI

### ISSUE THREAD

**Issue by edwinyoo44** [alejandroliu/pocketmine-plugins#27]
; zho.ini
"%1%-mode"=""
"%1% already registered"="%1% 您已註冊過"
"%1% has just joined"="%1% 進入了遊戲"
"%1% unauthenticated players were kicked"="%1% 因為驗證而被踢出遊戲"
"%1% unregistered"="%1% 取消註冊"
"**CENSORED**"="**CENSORED**"
"<nagme>"="no"
"Adventure"="Adventure"
"Creative"="Creative"
"DBM Error: %1%"="Error DBM: %1%"
"Database connectivity restored!"="恢復數據庫連線！"
"Database is experiencing technical difficulties"="數據庫連線出問題"
"Detected loss of database connectivity!"="檢測到數據庫丟失"
"Disabling SimpleAuth"="停用 SimpleAuth"
"Enabling SimpleAuth"="啟用 SimpleAuth"
"Fixing %1% for %2%"="修復 %1% for %2%"
"LOST DATABASE CONNECTION!"="數據庫連線失效！"
"Restored database connection"="恢復數據庫連線"
"SimpleAuthHelper has been disabled"="已停用 SimpleAuthHelper"
"SimpleAuth not found!"="無法找到 SimpleAuth"
"Spectator"="Spectator"
"Survival"="Survival"
"This command only works in-game."="這指令只能在遊戲中使用"
"Unable to find SimpleAuth"="無法找到 SimpleAuth"
"Unable to unregister %1%"="無法取消註冊 %1%"
"You are no longer registered!"="您已被取消註冊"
"You can only do this in-game"=""
"You do not have permission to do that."=""
"auth error"="驗證錯誤，請稍後在嘗試！"
"chat protected"="您不能在聊天窗發送密碼"
"chpwd error"="舊密碼錯誤"
"chpwd msg"="輸入您的新密碼："
"chpwd ok"="成功修改密碼"
"error registering %1%"="錯誤註冊 %1%"
"login first"="首次登入"
"login timeout"="登入超時！"
"logout completed"="登出成功"
"no spaces"="密碼不能包含空格與特殊符號"
"not name"="密碼不能為您的名字"
"one unauthenticated player was kicked"="一位未經驗證的玩家被踢出"
"passwords dont match"="密碼不相符\n請重新嘗試！\n請輸入新的密碼："
"re-enter pwd"="請再次重新輸入密碼"
"register.error.password %1%"="您的密碼最少需要 %1% 字符"
"registered %1%"="已註冊 %1%"
"register first"="您必須先註冊"
"register ok"="您已成功註冊！"
"registration error"="註冊失敗，請稍後在嘗試！"
"snob login"="其實您並不需要輸入 /login 指令"
"snob register"="其實您並不需要輸入 /register 指令"
"too many logins"="您嘗試登入太多次"

Sorry~~I forget how to use GitHub

**Comment by alejandroliu** [comment]
Included in commit 2c033e2
