### ISSUE TITLE
I'm try 2.1.0dev01 Version

### ISSUE THREAD

**Issue by rock2rap** [alejandroliu/pocketmine-plugins#28]
it's after run server
[Server thread/CRITICAL]: ClassNotFoundException: "Class aliuly\killrate\common\mc2 not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

an disabled it

**Comment by alejandroliu** [comment]
Only v2.0.1 has been released.  Anything beyond that is a Work in progress.
If you want to try the version currently under development from source you need to either create the phar using the mkplugin.php script or if you are using a FolderPluginLoader, need to run the maker script in the KillRate folder.
