### ISSUE TITLE
When could you to upload SimpleAuthHelper for API1.13.0??

### ISSUE THREAD

**Issue by edwinyoo44** [alejandroliu/pocketmine-plugins#29]
When could you to upload SimpleAuthHelper for API1.13.0??

My server is need it~~

((Sorry,my English isn't very well

**Comment by alejandroliu** [comment]
It already works on API1.13.0.  (php5).  If you are looking for a php7, I am not working on that yet.

Also, SimpleAuth needs to be fixed.

**Comment by edwinyoo44** [comment]
ww....
OK~I try it again
Because I try it that isn't work
