### ISSUE TITLE
TileEntityDataPacket not found

### ISSUE THREAD

**Issue by Awzaw** [alejandroliu/pocketmine-plugins#41]
Hi, since the very latest dev builds I'm getting:

27.11 11:44:15 [Server] Server thread/CRITICAL ClassNotFoundException: "Class pocketmine\network\protocol\TileEntityDataPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

27.11 11:44:15 [Server] Server thread/CRITICAL Could not execute task aliuly\killrate\common\PluginCallbackTask: Class pocketmine\network\protocol\TileEntityDataPacket not found

It seems that src/pocketmine/network/protocol/TileEntityDataPacket.php has been removed.

Thanks for a great plugin, and I hope you get time to update it soon!

**Comment by Pub4Game** [comment]
fix #42

**Comment by Awzaw** [comment]
Thanks :-)

**Comment by dterweij** [comment]
Please make a new phar release or a url to a fixed phar please. Too long to wait for a fix presented 25 days ago and still not a new release....

**Comment by Matthww** [comment]
https://transfer.sh/qyW47/killrate-php5.phar

**Comment by alejandroliu** [comment]
Currently in dev
