### ISSUE TITLE
GrabBag tried to access a constant that wasn't defined. Nether Reactor.

### ISSUE THREAD

**Issue by Arantxia** [alejandroliu/pocketmine-plugins#43]
PocketMine-MP Crash Dump Fri Dec 18 02:54:44 UTC 2015

Error: Undefined class constant 'pocketmine\item\Item::NETHER_REACTOR'
File: /GrabBag_v2.3.0.phar/src/aliuly/grabbag/common/BasicPlugin
Line: 67
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: GrabBag v2.3.0

Code:
[58]                    }
[59]                }
[60]                // The last class in the array implements the actual feature
[61]                $class = array_shift($class);
[62]            }
[63]            if(strpos($class,"\") === false) $class = $ns."\".$class;
[64]            if (isset($cfg[$i]))
[65]                $this->modules[$i] = new $class($this,$cfg[$i]);
[66]            else
[67]                $this->modules[$i] = new $class($this);
[68]        }
[69]        $c = count($this->modules);
[70]        if ($c == 0) {
[71]            $this->getLogger()->info(mc::_("NO features enabled"));
[72]            return;
[73]        }
[74]        $this->session = null;
[75]        $this->getLogger()->info(mc::n(mc::_("Enabled one feature"),
[76]                                                     mc::_("Enabled %1% features",$c),
[77]                                                     $c));

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #52 [Protocol 38; API 1.13.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux 1ca60a456195 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
LeetAuth 1.3.1 by ProjectInfinity for API(s) 1.13.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
xRulesx 1.0.0 by xFlare for API(s) 1.8.0
SpawnWithItems 2 by LDX for API(s) 1.1.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
BanItem 2.1 by LDX for API(s) 1.0.0
ArmorSpawn 3.0a by LDX for API(s) 1.0.0
Slapper 1.2.5 by jojoe77777 for API(s) 1.12.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
HelpOp 1.0.4 by hoyinm for API(s) 1.9.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
LiveSigns 1.2.1 by aliuly for API(s) 1.12.0
NoVoid 0.3 by rirititi for API(s) 1.0.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
GrabBag 2.3.0 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0
SimplePortals 0.0.3 by Falkirks for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWwtv20a2/isDJYvaC1FPS3ZUuICbONsATqxrO5vFrQpjRA4lxnyVM7SsFv3v9ztnhg8pbl7N
FtdZ7IpnZs77OeT+3jFRojqz4dFkcDQ4Hp0cdTuqKLKiM/u9Y7Y5ljrnt+dXV5dXnW4nUVrLFcHe
poEKo1QFwo+l1sLPUm1kasR3eebfKZNgbbGIjEoWi1f479nszfnNT+dXt1fnZ89vLq++A7YwiglV
/1+FXP4oV7f3o964N+jla1n0deH3ZRyV8ba/wvJSrvp+liRZ2v9R6sifx+UqSoEjBp3ObHr8R7eT
W9is4/Bh1c8CRYJMTgBemOrfH1iaPGuBCDAdtAD9vrhZKwHRjBMwSoUBRBaF3IooyWOVqNRoC/RN
KWMRKmnKQhGuYQvXU4vg1J691esoNAcWePg9bR7Vm5mPcf0YhQfaFHmm3fbuorOgv86hOD09FaGM
tToUNf6nqe5VO3oWyviPWgjFQaS1Ivrh6uen0S+Hh7Rj0mbXrCPt/ZBkQRkrTXuAOlUbR+eA17v1
eaYwrc8rsESQ4y/FaBFVdmJFVBZ66mO/n5WpOdhFxWeOK7uRcLT1VAwOxe+00ljBnVspc5GtVqo4
OPR+iNIwO0j82ez2YNF5c1mZTwuVymWsAqjZEmjsUyjsSBk4bnF6XGnYkdEIkyhLScoyjnn7ZHfH
44ykNTvnlgWRpariC+x0CdN0x5X3/4l9DP8Y/qOWbNGB3SyW449jwTbIjqAyhfQRQj93ngzEweFM
tKP7WhX3qvB+8Aup1y/KJD9YZlmsZHrY+aXbWalUFTKm8MMu0gdIDnvTQN2DgWUZxUFnNhkhbovM
ZH6GneOTbkfmEe8bjntD7FtFBo+Dz/zDgULexdGSzvSOewQoU0kJrnMRpeWDGPpyOpBHk+nw2USA
xLPewBsPPGY28sWT8ZH3dglPK8X167l4WUTi0jdiJEaj2eBkdjQUb2+ei9FgOBEPJ9NbhBb4X+dA
P+lNe0Oi95tKIVhnhOeBXb3NdEUfAH6I+aFOWpq0dKGUOSvNmn5XPFeg7o4OrWokFrJCk3HmRfZe
+eZVipQcmS2pn/X4s1XkgADOqzszU5Sq2wlUDkbpNNZ0FpoXbUAiOZMS/cWi4qL5RYk3kyTm/PL6
5t3l1cULgDZqqZHxOzPyesh2nuRm+y4ryNC1SC3grlADVldLKJv+d2UZfb0sFt1ioYiBDTGwWLyW
tohYWa5vzq5u3s7bknTWxuR61u/DD9flsocahLKk3ss0KDIg7Dfx4DlT9pElVD9B5VBF/9WbF+f/
7rdkhlp+LEDO5/WWXtrQXcUMp7t6Ob/P4msI+c000yL9uSqBRjabTU+BFcLaM3ck2cMVZeWHllQV
5BOmfngZSxTOtkAnXy+PxbZYOOL7Mn3MZa9zuUnfwdbUs+iWIHsLLXlGO5JcvPjPrl3+QvC9+A9y
7A7dLxFljow/V8WOFA1s1yCj3mjXINOjly8Hg2/mYbcW32JRM9D6+cUByCddsDVYKLJkSmpqR5WD
tMUd7WfPfZsN/qLNHNEvMdZZkWQF27rFfAvY5h/5XP53BWgIf5YMj9kIeLzXz+fn/ZYQFF+xzPOd
vFdB9h1ysivi++x9po7p75s5pbaUF4vks830RqHdL56vlTbtsNoB7yXvfWf7L1W1VPlE/qvt9SVF
bUdcaIUr23kQmbPCtLSyA/6gANwulZG3aAZvnwyOTvbamfPXMn+dBQH84hv5da4SmSeMcrHg6q/A
mSygsT0+v1RzLWb714mMY+9/n3vzR9S2Qwdq+0nF+WXeUpgD7KvqaFc562wbpcmOXp59vV4stsXC
0q7+93PU4FoAf7tUhV8ulbe+I32QZK9latuddpC0gLvZeNAbfzpEBn89RBIwwJb/ojJ6Ed2r62iV
tkVpYPtZ6+8J9hj0NdH/W8K9kZYyYPbvLGr38w7QUgTsuaOEIioig3/fKpQrfIuFpf0l1mQHxLRk
MC3tp6oKvOudo88ZS2xD+22Myy6aW17+hgllR3RoqLo8a5TTXKe19TL+Ir0Mv1pBnZfg86aQqQ5t
NdhTl7sd/FsiodIENTJ8BfhOFu0E3gLuNZz7ynop47uouNMfTw18wfcF2qH+Ktu0Hs+1VqmJgGZ+
3tJd6KgvFpo53oBjjBpt7j9zwHi+lmZvvmDQ/n3F+NPjxacmpdbw8pgafANqGo7c+ZOxg/hqfv3l
oYOR1I4wzwoDLX/gCxW8rY/BhxXvcXcYfMod2g73kcyyb+7cMlVZvOHxk0anCytZQEBEQ+WPfAnY
Q8JCL20iRbdbT+b1k3iepWG0EnTXvygW6ZObdSleKF8Mj8XwaDYczY5O6js12mDxeaTF04vrsriP
7mXcWiDmT4cnzyZjAq6wDV2dOh3QUyIfELdyC+ZOJwzRNHh4LptC/afDKYE3a8jkxZE2p1kYEsQq
2fu1VMX2NEtboMLHMQuhn71cao0cHZz+k/9ANTPB6WvkDL+QoZmJ+bmwN6N0RKZpVqa+cnx50l9H
6t6+O3BY0TJmGy+Mo9W6ZsfyLdMIDWW1z8KSbFkBwqwA4loF7uhaFoGfFfVzfp+7/UEUhpFfxmZ7
OmTl8Q2tyQpPK2OidKVPCRyDv9gawF6T1TCtVNDaQq+HTl+cvzx7e3HDgpQm87S8V44e3X7WCbW3
TWJyDUF5ml4XwStKUKd7cnIOAWnEnLeTLr3XczgLvYTRSlTsCVkofuGSpYrevEgjfFKwEUslotSP
S3T19KbmA6ckXNdZgpMhIdjHqWWouiKjsUYTSrEslLwT26wsHC4RhQJajsKIKUDBBTwKBQiI36hN
ja4fqFBCxVpssvQ7I2jElIUg1SQQ1oext2Bf0GsAK/dmrVJR5qhjARD0Fim5ukU2W6QCAYMK5MUA
gYtYpqtSrpSgN1usMhcWOsJznAF/9BsrlY5iRPOdFLsHwUCV4lTa20R3UY5xSPayYtWnJ/R82txm
4e2r68vb6fiZN7qlc1BjjWgmFshMq0WHCL1b80goTAZ+0kBASqFNwfo1VI5iaaA3XmZtMqfgA7+U
YZNiEox8JdaoxTEbOQFi6+ENSc6AgOt1aYKMosG+kCRmbMwJP840vbshts4osgSFOTgRrqKL+0iK
/6E4xxaO96rWzwTVHDp4vcY5yS81M3DjqFhTSYdIlBpOiGQMR2DpzuavsBM5PSA9NQse2FqCqQa9
fTdT4YHEggJWwF3hEcTqciucH2G7y0P1aqOGJ+8iKDpL4VIyCEShtPU8YhO+dgd2pEatomwj4G9L
RfqA0tWv9L4S5liht08FMmypxIEjiVR8COSWHvIf1wsP1qT3VTOsEuU3ZYK5j8LpTG9T/0bqO3h8
cYcA6tH6WxiB/bMSknatiwzZEC6B3borOLsIl4Xgsl2oIYHW7MszUguqD8GSMkXk0BbGfc0uA3kQ
XEX2gBxpFFQAcdjV05o10qpl51VIEUpbKBK7IjLfQXOm4FOBourAXrh3VhxAAthZjEgjLIPnpJwx
JopWSr/FlmP1X3G2hGKpEAsLhvclkaGclKiVXG4NGBLXlpUBE480mddGOmTaRMwYK1tQYbB4Kv1r
1ksYwV2QppCGU0YVIkdUFK35IUzJTrvKIEdGoUE6A50VM+kxYzMxWHCq4KxskGpk8P+cfWpqPsI8
lb+/xLw2Wc70Xaqq+XHYtEBIUROALOO4IZoVS8PB6MhyhV41yrgcUSxqIuhzQnbc1fE2BCmkmoB8
jHd4iAdlI43TeIYePkWEQm+UHf5MrVad6G1izvAU63bbggsu4UD0NZFs0xFRuKQUQhWOt/c+3Exi
uz4UKsyVT4XQfvxAvFod27O1ANCkynUj5njg5NSHjzLkpB5bqVeywFinPD+LY9u7UYQ9qlV2J2LF
nRHuDGI3kWnJJbfNBdqREr5w2K1ywp4zOG+weTUMq9yQNF7WE5e23vETPGKdlXFQMxIhg2xS0bBO
fity5hwCTgcDK6N48pIj4YPcyL5iT9dChUWWVCmWzrp1r52VWjaFEM50+67wiP+0zlEP7a/L9E5b
fV+w11NCZCBxRmMCSSNsT9vl8CzQgGi7yaMegHqZBhehqszsAuXZ1PH5IrPH9s1HRYA6JXusjcFS
cdu+gcxciDxf0hU6S+18oSJEC3X1/iiqRZoqQ7aoWze4Rmwr4VIaNP/UiEjqclEA4U8uK3EA2sbU
rdpktFR1TeR086SdvqoVCvxiawh3V3jDljNT7WOynqlYQVqZTG1WaWot9/NU6AKb7pwB7VkAHU89
8ROGFKj3FL0wHPf5/G0XZ8HBEvlnEwVmbbM2x3eN3mP0M3HsGoOmZdCsmNbWnjgLEE9rGYd9+vaF
u5hAwc8cIZC0/pel7YCsq3MLV6tPOn+g4KM2SMZdG9hE+F2UoouEWHAbxa5Ntf7tPJ1XnULTs1MT
RIc2yPULatjT3HOP7Z4MU5ZalquZazp+EENqNlxloa6Sl6uOsv6szHWaC2cKlJGmT9Sir400JRym
v/KtapHXAt0iWs1nO3ODqppI4huS2ImJtzr3InHZ4D6UaNjD3BHPHpmJBEsrN09AIL6VIXbhcnBS
TkpyBz8yJ01kpkUeyjQfcsMxyqZ78uby5nwmOOviP36J4SrFcMWI6m/tmD1HuWavNvHZjrV8zBHI
JE5W9iIuSeCEvMaQ54wGroRQKrOVidyIhliCu3Lkon4XXOUw2wtfK/cd4FJq1SJ2MESgPEKlK0ZY
GD62oIzfO+Sg1arNBbvDDWGm0crdcQiFxGTpUem3luQhtpluKRHwFETdE6UDGW/kVlvcDk/Lj3by
N7vRWUIf3rUKgHY9W8UEsU/YaGRAbqafM3H050dlAWhgebc4dquOGD4bPXqavStVdo5cKottqULK
RHw3QhmLzFBjtTcmrdRnM9+1vEfRpf4uonGZvmHN8q27GnC1qG5oOFGEfP9bpUWXxsIy5m2Zhqt6
FKKRb0sJj2AFzeNwDKCtVPU+o0nIxoaWCflKwrmSCkwt/54xSKGVMV7LByH39YIZyOf60PjDri3Y
Sa9kEJW6dczZQTruOEjtUed3tB/dCuUkupryyjyALzYMYtRW0hLhq7SmClrGm8Gu4r33IfMu/21k
xDM65vFSOfu68xz2DPc0jDUTJ1+FLc/yMnbY3G8qTXuIFynHpAftEdP2As5jP9KkSVJlQp8605WL
gw5deqCbr5mwzV1lUvoasszR7NiOzzokJw/baDhcwHJMpxxBQjqhx40kQjWQYTJZRvB8u8VdutkZ
fWaTEV0n0BeZwkJtjXVOYr3XdfJ1ciO/9uiCZxdSl5MdaL7O6YPVxg3WGdmeSfZa931ohJi/NEu3
CbX5HCEa+tU1ozS3uGXRLDPD8DUp5GqF6uMuB+prF+oR6bvUu8elsfwQOv0YP6Qv68ps4v3T8Am7
OrMGKFLPFeemA2RolrcujJ7TnSFfYqk4y6ladQV94ECXLeDEtWLoTEJ0ygrKRn1Kqc7TJldaS7IO
4rGFRLi3Bq0eokTDSR+lU4GrEp7DRhayyxV+vacUemH/iEriCOXGWuX8QVK9tQ/UsAC/Y2JWccNL
cHaalGfiZ/rpoch0eXT+hTDaLFi1Ie3bVhaimhfs0FbdQvM09tjlLQ+3XMU0dwwkdoJGIgKjrsS3
WGeqzAD/EnRpTaHLJamhNhMvL85uZqPvj7uTZw/D7vhh3B19P/w+QCW2WeuAXv3xZ+enJwOxgn9r
+3Q0OeTLbfVgVEoK4fc+z1GH2t8Bkw+1n1EQVvU7nNynze5B/xpHRo3tN8ue/T76N/sRs337vPTR
2azr/XR1mgayaAD2/6hRPZVFXD+EUczfmQK1ewkbmrxeXTVvlVZJA14jlO3HJ9j/Xu983cD6DuwH
1sPexLGbLO11b40CbeM2N42IRhLHQVsh1/MLxkKfHuY++r3m8BYq4a+o3S8x6RH/REx49KpoNJgM
xvj59BUN1P705GQ5XS798SAYT2U4lv74KAyCo+XxcrI8PjkO1QR/4ikozdekOP7shAlnOnpozOIG
erdhSAJfqdBNo4AyPRWGJ8vAn06Wg6WS4Ul4JAM1DQfT8OToRE2Do3EQBiejKdPT6yRrNKs5+PSu
pJFVJjab7E6lqEVFDXmn5B2yhlVUj74E3kp+kVJ9WvZblNsn+mTujz/+D8UwpvU=
===END CRASH DUMP===

**Comment by MichaelM04** [comment]
To fix this simply disable "get" option in grabbag config

**Comment by alejandroliu** [comment]
Can't replicate
