### ISSUE TITLE
0.13 error? 

### ISSUE THREAD

**Issue by RocoWayne** [alejandroliu/pocketmine-plugins#46]
I think that in 0.13 crash ...

09.12 10:15:45 [Server] Server thread/INFO Disabling Scorched v1.4.1
09.12 10:15:44 [Server] Server thread/EMERGENCY Please upload the "/CrashDump_Wed_Dec_9-09.15.44-AKST_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
09.12 10:15:44 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
09.12 10:15:44 [Server] INFO Fatal error: Undefined class constant 'NETHER_REACTOR' in phar:///plugins/Scorched_v1.4.1.phar/src/aliuly/scorched/Main.php on line 217
09.12 10:15:44 [Server] Server thread/INFO Enabling Scorched v1.4.1

**Comment by edwinyoo44** [comment]
Check your plugins

**Comment by RocoWayne** [comment]
PocketMine-MP Crash Dump Fri Jan 8 04:54:11 AKST 2016

Error: Undefined class constant 'NETHER_REACTOR'
File: /Scorched_v1.4.1.phar/src/aliuly/scorched/Main
Line: 217
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Scorched v1.4.1

Code:
[208]       if (!is_dir($this->getDataFolder())) mkdir($this->getDataFolder());
[209]       $defaults = [
[210]           "presets" => [
[211]               "short" => [ 30, 0.5 ],
[212]               "long" => [ 80, 1.0 ],
[213]               "fast" => [ 20, 1.0 ],
[214]           ],
[215]           "mines" => [
[216]               "block1" => Block::TNT,
[217]               "block2" => Block::NETHER_REACTOR,
[218]           ],
[219]           "settings" => [
[220]               "failure" => 385,
[221]               "rate" => 0.5,
[222]               "usage" => 5,
[223]               "max-speed" => 4.0,
[224]               "min-speed" => 0.5,
[225]               "max-fuse" => 120,
[226]               "min-fuse" => 10,
[227]               "rpg-yield" => 4,

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #55 [Protocol 38; API 1.13.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux mcpe9.netherbox.com 2.6.32-042stab108.8 #1 SMP Wed Jul 22 17:23:23 MSK 2015 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
DropParty 1.0.0 by HotshotHD for API(s) 1.12.0, 1.13.0
SignStatus 3.0.0 by xpyctum for API(s) 1.0.0
NoArrowPick 1 by CapainKenji17 for API(s) 1.12.0
InventoryClear 1.3 by CrazedMiner for API(s) 1.11.0
PerWorldChat 1.2 by EvolSoft for API(s) 1.10.0
1vs1 0.0.4 by  for API(s) 1.0.0, 1.1.0
Scorched 1.4.1 by aliuly for API(s) 1.10.0
Cameraman 1.1 by ChalkPE for API(s) 1.12.0, 1.13.0, 2.0.0
ServerAuth 2.11 by EvolSoft for API(s) 1.11.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
Slapper 1.2.7 by jojoe77777 for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
GoogleAnalytics 1.0.0 by  for API(s) 1.0.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
RealTime 2.1.1 by Guillaume351 for API(s) 1.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PVPMoney 0.1-Alpha by hm for API(s) 1.0.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
WorldMonitor 2.0.0.000.0 by Steven for API(s) 1.2.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
BattleKits 1.0.4 by Falkirks for API(s) 1.0.0
WalkingParticles 2.2.1 by CyberCube-HK Team & hoyinm14mc for API(s) 1.13.0, 2.0.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNW3tz2ziS/yo4ZeomuRJlUS/bmvJUeW1nko2d+Cxl8sdwywWRkMSYJDgEaFnZmu9+3Q2QBGVP
Yse5qk3mIeLR6OevuyHq3x0dp6Iz9UfjwWDiD8Z+tyOKQhad6b87epvDVOfs+uzq6sNVp9tJhVJ8
hWMfs0gs40xELEy4UiyUmdI80+zn92fzN2dX11dnxyfzD1c/w65lnOCWvVkoi3Atoutbvzfq+b18
zYs9VYR7PInLZLun7PzeBY8z2JcA/c504O//1e3kSbmCwWmnIgLzoYwEsjnoH8BEoAMdL9nL/4rV
dRQXL3/S61h5v66EPuWav5ZJJIqXr169YunNV6Z/AbqD/qGl9xMIyctEK3bE/sAZv29n4G8nL4QS
WgUddvSrnfabaVig1rLQdpoN+13W743Zv7q0ctBamchsVS08gIV+r18tHLYWLrmqKQ7aC0f1Qjsw
dnhNQZctTictsotEhje+mf8Hfp5O5+/nhsz+/ZWD1sq2xc2mg11mDh1mQGs6zlYuP4P+jphxUhbC
LBgejInGoK3dgmu7ANRqFrSVWqKvmhV2vq3LlN95KhciMmtGvb5ZNWqvijN3VX3W+B6tZanscf7A
kprcI+Ussmva+i3ylbeNRVIx1e2A9+uCh+Dqf3Re9NnLV1OWg96FRpsGwUwUt6Lwfg0LrtanZZq/
XEiZCJ696oDqVyITBU8wTGCViiXGkN+bROIWDl+UcRJ1pmMQKS+klqGElcODbofnMa3zhz0f1q1i
DY/9R/6BDQW/SeIF7unt93CgzDjCTOc8zso7loa5OOxlQq9FsZB3vVCmbNCb9IYDrz8aAJAs/P5B
74C98Nns4pJ9Apj5Z5mwwYD5+9PBEP5hF7N3EAD+mN0dTK4nIzgiX+dwwBjIDODpi8hAsg5S7ZvJ
a6kqBmCAHhJ6qOFFoZpOC5lf8kJv8cFy3Yx1W2rsE21eagh0hfZ5IzUEvX5zironJf6BWhzQOlJn
H2dExhcJYNhUF6XodiKRA7dIAOaUXOpTdyDlBHwR8JAjD0HgspNIjnJefpjNP324Oj+FoY1YqFgD
31mZJCDcLF5lM811qRyRnEFXpuF9me7ybajLtCVR//vlaA4G33WZeIQk7+Ux5KbNZRzeOKK4o44s
fkuKE57D+e9E9jkGRLtnne8Uxjk6CKq09W053ma3ItOy2J5AoBaOKDsTrjS9YVuegn8R0QVAQNGW
xv9+aYKgff5TRLoUxSdZJNHJmmtHoNZwO3gGbTc7u5XJDBhrS/MMR3OP3pVkNj++mn+8dOXorLXO
1XRvb7PZ9AQwg3R7+gbhwb9VviMUPbrCAJe9UUuc3WCh6P9+WcDO8TK+i2UQyEzcKonI/yETvyv4
zyNRoCqcHAxoainXMCPCfMc0pj77YYYx5IKgqvee4mYnwHnBU545YjRjbTl2pAA/SG4uz76CzJCN
7yHbkifqsYKFeEIQhBU/QeCy9jXpyPnA94hCD6puNBgl9mMQwDVZM+gKO4C4f0w4PcMFm5OrmsNy
8Y2QejiiCF/O+Wrl2rEe27HjbkY6F1DWRB+WFyc75nyO8erTg+AcJBLFY0yGeAHF0bpcYA2z5zK2
14gD8l7Mcr7J3ARcjbRlHf8/W9Ge+kw8nCU8z4WbuKqRHYjv7bfl+Sw/S7GPf76egp9iOGWODoL0
8ShSKi3T40QU2jVJa7gtyeQxdnlGIeEeDbDRZuS7Igxrq0voP03x71R9dnA3xnbS8eFhImQGeJSt
WkJiQ/C9lqopHh6a2s+w8ij8fyjcHB73HMlA+N+kXCXiOOPJVseha+Pdma8X9D8KXE55cfN+qMC0
O+ffG3icA1Nhcwktmwjdaqs13M4Pg10Q/buk3n2mJ1fZfYO85IaXp8CNY1+eiM88g8YHSO41Pa9n
u7U9XQixl3KlRbHXEh3r0bIQUAGmru2bsV2Y2nH+yej1637/hwX3taEXBDUDzscna4V2Wg00VEDk
K8GTOd3m1RLXQzvFwm5t9FsZJwkvUzEc+z8so1aHG+uf4D3h47z7LJSZTLfHl28dUZzBtjD93mFb
GCiOF/Bv5+9q8C6ZvPq/T/8f2uehfR7Z59Ez4M7yEQTCsA7MBEFLjMf0Vb9fXgAR9zaiHmq3IL53
nORr3tbFOn1QDSMr5o+tf+OlFjwF37YMNp+egGqwPtay2EW1anjX9vC3f+/KYqYF9LEtyZ9TYbgM
PKVZueDZlva26r5mcFeW4dPbrqeIUSEztCNbQmf1FGHmPJ/LU+lIUo3sJpodbHkNLc0PwxTNcy0j
aIObwx8PKLO1zO8jCo3ummL/25Dy7aLVxawn4IQChmqgsNw96povzRNxYb6iaV/1tSZal0qDlpin
pZY/zlbtc7Hi2+HjMZZTSmQ6hlOh1XNM5w7vVrLDh7pFZboyNgeE+nG9h8vHj+obW7I5ziuS5AHn
xdH/KOcFhhrnNdw9ws7/4Fon4l3c6secwd0yfXQfY+LiRj3Td9tFxiVVnCZ/NQIviKmbGPu0FoOP
SXDIZrbCu/s4TFpBem/qG6h6sl2I4qRcCO/NO3Jq9t9sLbdxlvqjNGzb+vtze+d3nsVq/f7SUcAu
p0HwAO+PqWygdt29La6G2uYe7ob0Q/X5ty5FnOr/vpiveajhNAUNROdv6nZzjexw+LyqnYj8hV89
8QKEhxamMgDdrfWgc8qh/Y/RSTovLusndiKzZbxi+KV6kL2Yr0v2T56xfeb3p6P+dDxmx+9mc/xq
bBJkqdTR0W/H848nV8ev5wzg7+PsOMg2a2DTS2Klj+RyGWQ8y2SZhdhY8a0oPB6uYyigUoAhdSSz
IFN4aeTZZg70dITEeZLIjbdM4tVaO6vAYVLwK2cklQvzuAJBUxmJo36QLWUBB9YjxMeaF1EoC/uU
3+a0K4qXyzgsE7098oEGfaEJhZhXfYt8FGQJcJvAgIjqB3x34ej07PXxx/N5kBmv8P4sRbElonag
gHg3p+GnXg4tClRG0dH/0B+QERKip/itoE1GYvO1JQ3cxmLjRTG++RAKOFpm+M6CZyRy5M+wRTU6
WAMkUvFlFpgvb+P8aOBPAJQnvcEQgr2eyGWhjwaT/sEhGJPfWQOpo0m/khMj5+hcLhZYYzc9cm+b
Jug4DAs8fDsDfKYEvYHxyHUY6J9ZgEOWLy7Bmdh8LZRglWIZLwQDWRkgoIIPXLMQXUWzhWBxFiZl
JCL4wO65LNKayRR2LpHALk3Fl6LLJKpRIUm2KAS/YVtZFpYWi5cMtBgvYzoBnKIAz4PiFQi/F5ua
3F79gsZGZj9rhjeBvGBothSEDcFiW2Cf4cseRu7NWmSszFcFj4BALyAjGGLTIGMQUIWA2IAh4CLh
2aqEYoXhqyakMmsXFcNzIoF+/IWUiltP1iK0UrQ3AgMVIoist4lv4lxEMe/JYrWHT3vn4ELXcnn9
dvbhejI89AbXuA/UWBOasgCgbRV08KBPa3JBpiXwk0UMpGRKF6RfXfBMJVyD3miatEmcAh/wSWgy
aSRu41CwNc+ihIycAmETk82RlB9gXK1LHUn0ZFO7ITPmKwAWJlLhqxHI1jGGB0NYAU6YvaRhtzFn
/4txB0so/qrrmylDiMaNUONuGKd3iCRwY08xpuKWECsVOCHAOTgCSQc5GlZCSohQT82Ed4vvFCjR
kD+jWK/ogMQMQYaBu4JHIKuLLbN+BMstMtSzjRpefIpB0RDjW8ajiBVCGc9DNsHXboAdrgDaETcZ
+NtCoD5A6eLPkidojlUMbSm75Ukp2Et7JED1KyBuzgNEEhjzHlhztRLFFGbx5PdlCukew+lYbbNw
ztUNeHxxAwHUw/mPYATyz0pIXLUuoJgpwSVgteoyQh1m8RNctgtqSPEdJsyzpBZIYDiWlhlEDi4h
2jNyGZAHgquQd4DuWoAKQBxy9axmDbVq2Hm7xAjFJRiJXRbrn0FzuqBdkcAsQl64s5e9BAnAzmyA
GiEZPCvllChhtGLCKLYUq78lcgGKxVzOzDB4XxprxKRUrPhiq4EhNjOs9OnwWKF5TaSDTJuYGCNl
M0R3Q6fSvyK9LGNwF4ApvFQgUkvAiOpEY34Qhl43YisJckgMDdQZnLMiJj1ibMr6AUEFobIGqOHR
fzj7WAp9hXlM2c9iXmmZ0/kWqmp+LDXFIKQwLwPKWG7wzIolvz8YGa6gtIslpSOMRYUHhgTIlrs6
3nw4CqAmQh+jFR6+SWYijWBcQveVQYSC3hAd/k6tRp1QSyWE8BjrZllACRdpQPQ1kWzgCE/4gBCC
GY6W9+4vRrFtIQsqzEWIiVCRWpBXo2OztxYANCly1Yg57Fs51asHGbJSD43UK14swP5eKJPE1HgY
YQ9qldwJWbF7mN0DsZvyrKSU63IB5UgJvvCqW2HCjjNYbzC4ulxW2JA2XtZjH0y+oyfwiLUsk6hm
JAYE2WSsYR39luXEOQg46feNjOzFa4qEe9hIvmJ210ItC5lWEIt77bznopJjUxDCmm7XFR7wH2cf
FnXhusxulNH3OXk9AiINImfYZ6A0zBR/XQrPAgoQZRZ5WANgLdPQQlKVmW2gHE4sn6fSbNs1HyYB
rJTMNpeCOcUu+wEyUyLyQugyhJHa+kJ1EE7U2furpIIMinG0RV26gWskJhNCnw5tDBYiHKtcSIDg
TxaVKABNYWpnDRgtRJ0TCW5euPBVzWDgF1uNtLvM8x1nxtxHx3q6YgVgZTwxqNLkWqrcMdFFBu6s
Ac1eGLQ89dgb6K1AvUdQC4Pjnlx+7MJe4GAB+LOJI702qE3xXZP3iPyU7dvCoCkZFCnGWdpjxxHE
05onyz0o8k0VEwnwM3sQHGn8T2ZuQNbZ2aHl1Elndxh8WAbxpGsCGw/+FGdQRYJY4DaCXBtz/cfL
7LKqFJqaHYsg3LQBrA+wYM9yzz66NRl0h2JRrqa26PiV+Vhs2MyCVSVNVxWlIhxbi6rSDKwpII00
daJie4peSeyyvVVoVAu4Finn0KrfbPUNoioikW+QxHRMtNS6F4pLBg9BiZo8zG7xzJYpS2FqZfsJ
EIguMZDdW3wVwIASb9EH5MSOTDvHgzL1fW4oRsl0L95/mJ9NGaEu/BOW0Fxl0FwRIbqjRdMRe/bk
mr3axMcta9FX8KKSlbyIUhJwgl6j0XMGfZtCEMpMZkI3wgYbx206slHfHq4wzNTCMwxXFHDBlXAO
e+lDoDxwSpcNYMJ/aELosPeKglYJlwtyhzlSxtbKNt1MADCZ8zD1G0tSE9t0twgE1AVh9YRwwJMN
3ypD29Jx/KiF3+RGx6ksMzcBKFuzVUwg+0gNWwbAZvw4ZaO/38oLGI0M74ZGO+sw/3Dw4G7yrkyY
PnIhDLWFWCIS0b0GIhaaoaZqbjsc6DPIN+O3kHSxvouxXcafjMh8a68GbC6qCxoCiiV9pV/BooWx
ZZnQMqnAVT0M0Tg0qYRasAL7cXAMIFup6rPETsjEhuIp+kpKWIkJppZ/xxio0MoYF/yO8V29QA8U
Un5o/KFtC3LSKx7FpXK2WTtwyx0Fqdlq/Q7XQ7WCmIQ3al6ZR+CLDYPQagtuDqGruyYLGsabxq7i
vXefeYt/Gx5Tjw79eCmsfe1+Cnsa9xQYa8oOvotaLvMysdTsZ0xNO4SDjGLSA+0h0+bq0CM/UqhJ
VKW9PatHfQsPeCs3Zaa4q0yKP3socyh2TMVnHJLAwxQa1U0cJEfcZQ9EomN83HA8qB6kMZ4uYvB8
s8ReCJoefWrACK8T8KcXzIyaHGudxHivreRrcEO/9vCCpz1Sp5PWaL7O42wpGzdYS7Q9Hdlz7vug
ECL+MpltUyzzKUIUvlJUM4p9i51mzTQxDL7GGV+tIPvYy4H62gVrRPwBys3D0hh+kJx6iB/Ul3Fl
MvHubvAJMzs1BigyzybnpgKkUZk7F0YneGdIl1gikTlmqy48gwR4Q6erUgwqkyVUygKUDfkpwzyP
i2xqLdE6EI8OEWa/dHBqiBIKTqVNgqsAz1JDC5npir7aUQq+lfeASpIY0o2xytkdx3xrHrBgAfqW
iWnFDU2Bs2OnPGV/4EcPkkyXWud/IUWDglUZ4t62khBVv2Catur+nLqxhy5vqbmlLKaoYkCxUygk
YmDUpniHdTqVGKBPDC/hMXQpJTWnTdnr8+P5dPDLfnd8eOd3h3fD7uAX/5cIMrFBrZf4NleICHN0
0Gcr8G9lnkZjSNGdbkfcaZGhQuhrsxPIQ87PfdCFnEdIB6v6+608xKX2Qf2ZxFoMzU+TPPMzqC/m
t0rmXZhFCHXNul6PF6dZhD/SqAbMryKrp7JI6odlnGh8KxZfxjEvGi11Xs+u0ubzGqLXfJMJiz6r
+j00/JIvXZi73Hox1ITbXDcSaI4MRY64s8tzOhU/5yHUcs3eLQhMv4Syn9i4h9yh5MzDr4kG/XF/
CB9/egt2Ww73h4KPo2g8Hh7sT/xRf8IP+oMBHy0O+HB/NPIPFoNRX7Cf8PvRNaqFvlekg6WK7xql
22bdLvBR0CuxtJ0mjNJ5B2K8DDlUqiM4tr/c3w/3Dw4m4zEcPTwcDMWwvzjcP4wiOk+tU9moUFFg
qbaksVE+LNbyRmSQZ4p65JPgN4AIRlH0ovWW05ckvn0f7kucm6dBb9T566//A4q+y7g=
===END CRASH DUMP===

**Comment by Matthww** [comment]
This is because of the Nether reactor is removed try to replace it with a other block!

**Comment by RocoWayne** [comment]
Oh, i see! 

With what other block can i replace this?

**Comment by Matthww** [comment]
Choose one you like!

**Comment by Matthww** [comment]
It can be everything as long as it's a block even a dirt block!

**Comment by RocoWayne** [comment]
I will try right now!

**Comment by RocoWayne** [comment]
Works just fine
