### ISSUE TITLE
WorldProtect - BanItem doesn't work properly for every PE device

### ISSUE THREAD

**Issue by SleepSpace9** [alejandroliu/pocketmine-plugins#47]
Hi,
I recently had to update the **BanItem.php** so that it also properly blocks Items (in my case Item ID 383 - Spawn Eggs) on all devices. Because some of the players with android device could place spawn eggs  although I banned this Item. For me (Windows 10 Edition and on Amazon Fire) and most other players it already worked before my update.

I was inspired of another Plugin -> https://github.com/LDX-MCPE/BanItem/commit/473d455c7df8228a340583fd32035cd9ba840e73

So this is the additional code for WorldProtect's _BanItem.php_:

``` php
...
use pocketmine\event\block\BlockPlaceEvent;
...
        public function onBlockPlace(BlockPlaceEvent $ev) {
                if ($ev->isCancelled()) return;
                $pl = $ev->getPlayer();
                $world = $pl->getLevel()->getName();
                if (!isset($this->wcfg[$world])) return;
                $item = $ev->getItem();
                if (!isset($this->wcfg[$world][$item->getId()])) return;
                $pl->sendMessage(mc::_("You can not use that item here!"));
                $ev->setCancelled();
        }
...
```

Maybe you could merge it into your release. The Mobs generated by spawn eggs left my server unusable. There were players who liked placing a zombie army killing my server. :boom:

**Comment by alejandroliu** [comment]
Currently in dev.
