### ISSUE TITLE
Can't load Killrate :(

### ISSUE THREAD

**Issue by nooneusethisname** [alejandroliu/pocketmine-plugins#57]
ClassNotFoundException: "Class aliuly\killrate\common\mc2 not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by Matthww** [comment]
Try this phar:

https://transfer.sh/qyW47/killrate-php5.phar

**Comment by XiangZhao969** [comment]
The plugin can be loaded now, but the [STATS] sign, [RANKINGS] signs,... still don't work
