### ISSUE TITLE
SkinSaved

### ISSUE THREAD

**Issue by MrDoni98** [alejandroliu/pocketmine-plugins#58]
Can you write a separate plugin to save the skins of players in .png ?
I would be very grateful.

**Comment by RocoWayne** [comment]
Great idea

**Comment by alejandroliu** [comment]
GrabBag should allow to save skins in .png (if using PHP7).  Unfortunately it is not fully tested (and your mileage might vary).
You can disable all the GrabBag commands and just keep the skin related one.

Otherwise you can re-use the code in libcommon : SkinUtils...
