### ISSUE TITLE
ItemCasePE / Fatal error: 'continue' not in the 'loop' or 'switch' context in phar:/ItemCasePE_v1.0.8.phar/src/aliuly/itemcasepe/Main.php on line 184

### ISSUE THREAD

**Issue by jhelom** [alejandroliu/pocketmine-plugins#63]
hi

Problem in PHP7.
please upldate.

`Fatal error: 'continue' not in the 'loop' or 'switch' context in phar:/ItemCasePE_v1.0.8.phar/src/aliuly/itemcasepe/Main.php on line 184`

**Comment by alejandroliu** [comment]
Fiexed in dev
