### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kaitododoyt** [alejandroliu/pocketmine-plugins#67]
[Server thread/CRITICAL]: Error: "Undefined class constant 'pocketmine\item\Item::NETHER_REACTOR'" (EXCEPTION) in "/GrabBag_v2.4.1.phar/src/aliuly/common/BasicPlugin" at line 69

**Comment by Matthww** [comment]
Go in the source and change the NETHER_REACTOR block to some other block 

The Nether reactor got removed you know...

**Comment by themonsterkill** [comment]
Were in the source?
