### ISSUE TITLE
[PERMISSION] Can I Use some of the Empty World Generator Code?

### ISSUE THREAD

**Issue by ghost** [alejandroliu/pocketmine-plugins#71]
So, Im Re-Creating a Working Skyblock Plugin, but it used to make the Island badly, so im Creating a Generator, but i want to use Your Empty world generator code to Create the empty world and Populate the chunk with an island, since idk anything 'bout PM World Generator, so i WILL give Credit to Plugin Developer(aliuly i guess?), and Mention this plugin if wanted to, Thx!

**Comment by alejandroliu** [comment]
Yes, you are free to re-use the code.
