### ISSUE TITLE
ManyWorlds Int class incompatible with Genisys PM

### ISSUE THREAD

**Issue by frankblob** [alejandroliu/pocketmine-plugins#72]
Updating ManyWorlds to Genisys-compatibility would be very nice. Currently I use ClearSky for world fixes and port them to Genisys when I'm done. Below is the (minor?) problem that causes the issue with Genisys PM.

**From Genisys start log:**
_[13:56:10] [Server thread/INFO]: Enabling ManyWorlds v2.0.3
Fatal error: Cannot use pocketmine\nbt\tag\Int as Int because 'Int' is a special class name in phar:///home/genisys/plugins/ManyWorlds_v2.0.3.phar/src/aliuly/manyworlds/MwLvDat.php on line 36_

**OS info**
_Genisys version: 1.1dev #269 [Protocol 46; API 2.0.0]
Linux 2.6.32-042stab108.8 #1 SMP Wed Jul 22 17:23:23 MSK 2015 i686
PHP version: 7.0.2
Zend version: 3.0.0
OS : Ubuntu 14.0.4-minimal_

**Loaded plugins:**
_WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
FireBlade 1.0.2 by aliuly for API(s) 1.10.0
RestartMe 1.2.0 by Gamecrafter for API(s) 1.10.0
AntiCheat 1.4 (b5) by DarkWav (Darku) for API(s) 2.1.0, 2.0.0, 1.14.0, 1.13.2
ZipPluginLoader 1.1.3 by aliuly for API(s) 1.10.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
GrabBag 2.4.1 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0, 2.0.0_

**Comment by alejandroliu** [comment]
Currently in dev
