### ISSUE TITLE
LiveSigns incompatible w/ ITX Genisys core

### ISSUE THREAD

**Issue by frankblob** [alejandroliu/pocketmine-plugins#73]
**Server startup log error**
_[10:05:22] [Server thread/INFO]: Enabling LiveSigns v1.2.1
Fatal error: Cannot use pocketmine\nbt\tag\String as String because 'String' is a special class name in phar:///home/genisys/plugins/LiveSigns_v1.2.1.phar/src/aliuly/livesigns/TileUpdTask.php on line 10
[10:05:22] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed._

**Crash dump**
Genisys Crash Dump Wed Apr 13 10:05:22 CEST 2016
Error: Cannot use pocketmine\nbt\tag\String as String because 'String' is a special class name
File: /LiveSigns_v1.2.1.phar/src/aliuly/livesigns/TileUpdTask
Line: 10
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN : LiveSigns v1.2.1

Code:

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.1dev #276 [Protocol 46; API 2.0.0]
uname -a: Linux routerus 2.6.32-042stab108.8 #1 SMP Wed Jul 22 17:23:23 MSK 2015 i686
PHP version: 7.0.2
Zend version: 3.0.0
OS : Ubuntu 14.0.4-minimal

Loaded plugins:
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
FireBlade 1.0.2 by aliuly for API(s) 1.10.0
RestartMe 1.2.0 by Gamecrafter for API(s) 1.10.0
LiveSigns 1.2.1 by aliuly for API(s) 1.12.0
AntiCheat 1.4 (b5) by DarkWav (Darku) for API(s) 2.1.0, 2.0.0, 1.14.0, 1.13.2
WorldGM 9 by Exxarion for API(s) 1.12.0, 1.13.0
ZipPluginLoader 1.1.3 by aliuly for API(s) 1.10.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
GrabBag 2.4.1 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0, 2.0.0

**Comment by alejandroliu** [comment]
Currently in dev
