### ISSUE TITLE
GrabBag v2.5.0 phar URL -> 404

### ISSUE THREAD

**Issue by frankblob** [alejandroliu/pocketmine-plugins#76]
https://github.com/alejandroliu/pocketmine-plugins/releases/tag/GrabBag-2.5.0 leads to a 404.

**Comment by alejandroliu** [comment]
Where was that link?  I am still busy fixing GrabBag... so I don't have 2.5.0 ready

**Comment by frankblob** [comment]
The link is in the readme :)

**Comment by alejandroliu** [comment]
Ah...  thank you... that link is updated automatically.  It probably leak through when I did a merge from dev to master (prematurely).

I will try to get some pre-releases this weekend so as not to have 404 links...
