### ISSUE TITLE
KillRate optimization

### ISSUE THREAD

**Issue by legoboy0215** [alejandroliu/pocketmine-plugins#78]
Can you use Async tasks for MySQL querying?

**Comment by alejandroliu** [comment]
Last time I tried to do, I was not able to achieve that.

**Comment by legoboy0215** [comment]
WHAT?

**Comment by alejandroliu** [comment]
It doesn't work.  I don't know how to make it work.

**Comment by legoboy0215** [comment]
Hm... That was what @PEMapModder did well at. Take a look at HereAuth?

KillRate creates most of my lag :P

It's ok though.

**Comment by alejandroliu** [comment]
Yeah, that code started asynchronously from the start.  KillRate started using SQLite so it did not need async, and later MySql was added.  So short for a major rewrite of the db handling code, it is not possible.
