### ISSUE TITLE
Suggestion: Enchanting and Enchantment Shop

### ISSUE THREAD

**Issue by DaPigGuy** [alejandroliu/pocketmine-plugins#8]
Can you make a plugin that lets you enchant stuff? For example: I do /enchant fireaspect while holding my sword and it will enchant it with fireaspect, all enchants are saved btw. Enchanting will need op or the perm node, but if you have the enchantment shop, you can buy an enchantment for your tools. Enchantments will cost ingame money or points. The points are from KillRate while the money is from EconomyAPI, PocketMiney, MassiveEconomy, or GoldStandard (You get to choose wat you use in config, default is EconomyAPI). You can also choose wat tools or items can have an enchantment.

Config Example:
# EconomyAPI, PocketMiney, MassiveEconomy, GoldStd, or KillRate

Currency-plugin: EconomyAPI
# What tools can have the enchantment

enchantments:
 fireaspect
 -item id
 -item id
 -etc.

Enchantment Shop Sign Format:
enchant
money amount
enchantment
enchantment level

Then it will change to:

[Enchantment]
$money amount
enchantment
Enchant Lvl: Enchantment Level

**Comment by DaPigGuy** [comment]
I would like all the enchants from PC.

**Comment by alejandroliu** [comment]
Not a bad idea. The Problem is that there is not enough metadata in the MCPE inventory to save this.  Any ideas how to solve that?

**Comment by DaPigGuy** [comment]
Hmm... What if we make it itemid:50 (damage value...)

**Comment by alejandroliu** [comment]
No because you probably be using it for weapons and stuff which already use the damage value. For example if you say damage 50 is enchanted then if you break a stone with your sword you will loose it or you could get an enchanted tool by breaking stuff.

**Comment by DaPigGuy** [comment]
Any ideas?

**Comment by alejandroliu** [comment]
Sorry, I am not able to implement this.

**Comment by SuperDude36** [comment]
As far as I know paper has paper:30000 and does not crash the game.
