### ISSUE TITLE
CRAASH

### ISSUE THREAD

**Issue by LewBr** [alejandroliu/pocketmine-plugins#82]
01.05 05:35:58 [Server] Server thread/CRITICAL ClassNotFoundException: "Class aliuly\manyworlds\common\BasicPlugin not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by alejandroliu** [comment]
Where did you ghet the manyworlds Phar file?

**Comment by LewBr** [comment]
From here, i just compiled the file, and i used php7 genisys but does't works! (sorry bad english)

**Comment by LewBr** [comment]
I need this plugin urgently!

**Comment by alejandroliu** [comment]
If you are creating the plugin from source you must use the "mkplugin.php" script.  Otherwise you should use the officially released phar file.

**Comment by LewBr** [comment]
I use the officially phar alejandroliu!

**Comment by alejandroliu** [comment]
You wrote:

```
 i just compiled the file, 
```
